### PR TITLE
Device search improvements and libusb dependency

### PR DESCRIPTION
**Pull request by themarpe**
Closes: #10

TODO:
 - Document libusb dependecy and licence of it (#37)
 - MinGW support if straightforward

### CODE REVIEW

**Comment by themarpe** [comment]
@wstnturner 
MinGW is currently broken because of libusb - if you are up for it, do you mind giving it a check and try compiling it with MinGW?
https://github.com/luxonis/libusb branch `cmake-android`  
Some (maybe relevant) info: https://github.com/libusb/libusb/issues/695#issuecomment-817326633

**Comment by westonturner-vr** [comment]
> @wstnturner MinGW is currently broken because of libusb - if you are up for it, do you mind giving it a check and try compiling it with MinGW? https://github.com/luxonis/libusb branch `cmake-android` Some (maybe relevant) info: [libusb/libusb#695 (comment)](https://github.com/libusb/libusb/issues/695#issuecomment-817326633)

When building against Msys2's libusb package I see an error not due to libusb:

```
...
D:\XLink\src\pc\protocols\tcpip_host.c: At top level:
D:\XLink\src\pc\protocols\tcpip_host.c:268:18: error: conflicting types for 'tcpip_close_socket'; have 'tcpipHostError_t(SOCKET)' {aka 'tcpipHostError_t(long long unsigned int)'}
  268 | tcpipHostError_t tcpip_close_socket(SOCKET sock)
      |                  ^~~~~~~~~~~~~~~~~~
In file included from D:\XLink\src\pc\protocols\tcpip_host.c:14:
D:\XLink\src\pc\protocols\tcpip_host.h:73:18: note: previous declaration of 'tcpip_close_socket' with type 'tcpipHostError_t(int)'
   73 | tcpipHostError_t tcpip_close_socket(int sockfd);
      |                  ^~~~~~~~~~~~~~~~~~
...
mingw32-make[2]: *** [CMakeFiles\XLink.dir\build.make:136: CMakeFiles/XLink.dir/src/pc/protocols/tcpip_host.c.obj] Error 1
mingw32-make[1]: *** [CMakeFiles\Makefile2:82: CMakeFiles/XLink.dir/all] Error 2
mingw32-make: *** [Makefile:135: all] Error 2
```

My Msys2 environment is up to date, XLink was configured successfully with:

```
$ cmake -S. -Bbuild -D BUILD_SHARED_LIBS=ON -G "MinGW Makefiles"
-- The C compiler identification is GNU 11.2.0
-- The CXX compiler identification is GNU 11.2.0
```

I'm getting many more warnings out of `XLink\src\pc\protocols\tcpip_host.(h/c)` on this branch versus master for what its worth. Would be nice to see no other errors before bringing in a custom libusb library...

I can look at getting a successful configure with the luxonis/libusb, but it also looks like there are more issues with this branch than libusb.

**Comment by wstnturner** [comment]
> @wstnturner MinGW is currently broken because of libusb - if you are up for it, do you mind giving it a check and try compiling it with MinGW? https://github.com/luxonis/libusb branch `cmake-android` Some (maybe relevant) info: [libusb/libusb#695 (comment)](https://github.com/libusb/libusb/issues/695#issuecomment-817326633)

Looks like there were a couple issues, one preventing successful configuration (libusb config.h was only generated for MSVC on Windows). That should be addressed by: https://github.com/luxonis/libusb/pull/1 . The other issue was more tricky, adjusting the include ordering of the libusb library header file (moving it above the XLink platform includes) resolved some kind of platform definition error. This should be resolved wit: https://github.com/luxonis/XLink/pull/43

**Comment by wstnturner** [comment]
I'm curious what the plan is regarding a custom libusb dependency. Are the changes being made to support this branch going to be fed back into upstream? What about licensing considerations, it seems like static linking would force this XLink to LGPL. Also I noticed when building this branch on linux and the hunter provided libusb dependency with a dynamic linking configuration `-D BUILD_SHARED_LIBS=ON` I get a link error.

**Comment by themarpe** [comment]
Thanks @wstnturner 
Going through it now...

> Are the changes being made to support this branch going to be fed back into upstream?

Partially... the required changes for Android are will most likely be added as part of https://github.com/libusb/libusb/pull/874

> What about licensing considerations, it seems like static linking would force this XLink to LGPL.

See: https://github.com/luxonis/XLink/issues/35#issuecomment-1007131283 and https://github.com/luxonis/XLink/issues/37
We'll default to shared library for libusb, so one can still statically link with XLink afterwards and not "pollute" downstream dependencies. In the end of the day, this default configuration will be exactly the same as installing libusb development package and linking to it. (as is done now for macOS and Linux)

>  Also I noticed when building this branch on linux (Ubuntu (WSL)) using the hunter provided libusb dependency and a dynamic linking configuration -D BUILD_SHARED_LIBS=ON I get a couple link errors (relocation R_X86_64_TPOFF32/R_X86_64_PC32 against <symbol> can not be used when making a shared object; recompile with -fPIC). To be fair, it could be due to WSL.

Hunter limitation, `-fPIC` flag isn't properly detected and same "toolchain id" is being used (See: https://github.com/cpp-pm/hunter/issues/206, didn't have time to fix it...) - To resolve, clear cache when switching between shared and static build (rm -r ~/.hunter) or use a separate `-D HUNTER_ROOT=[build/.hunter]` when building for either.

**Comment by themarpe** [comment]
Merged both and updated this branch - all checks pass!
Thanks @wstnturner !

**Pull request merged**
